# Generated by Django 5.2 on 2025-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_name",
            field=models.CharField(
                blank=True, help_text="Введите телеграм-ник", max_length=50, null=True, verbose_name="Телеграм-ник"
            ),
        ),
    ]
