# Generated by Django 5.2 on 2025-05-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_change_content", "Can change content")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
