# Generated by Django 5.2 on 2025-04-23 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "table_number",
                    models.PositiveIntegerField(help_text="Укажите номер стола", verbose_name="Номер стола"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Укажите расположение стола",
                        max_length=200,
                        null=True,
                        verbose_name="Расположение",
                    ),
                ),
                (
                    "photo_table",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото стола",
                        null=True,
                        upload_to="photos/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "table_capacity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите сколько максимум человек может поместиться за столом",
                        verbose_name="Вместительность стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date_reservation",
                    models.DateField(
                        help_text="Выберите число, на которое хотите забронировать столик",
                        verbose_name="Дата бронирования столика",
                    ),
                ),
                (
                    "time_reservation",
                    models.TimeField(
                        help_text="Выберите время, на которое хотите забронировать столик",
                        verbose_name="Время бронирования столика",
                    ),
                ),
                (
                    "count_people",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Введите количество человек, но не меньше 2x",
                        validators=[django.core.validators.MinValueValidator(2)],
                        verbose_name="Количество человек",
                    ),
                ),
                (
                    "wishes",
                    models.TextField(
                        blank=True, help_text="Напишите Ваши пожелания", null=True, verbose_name="Особые пожелания"
                    ),
                ),
                (
                    "count_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Введите количество часов, на сколько хотите забронировать столик, но не меньше 2x",
                        validators=[django.core.validators.MinValueValidator(2)],
                        verbose_name="Количество часов брони",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите номер стола, который хотите забронировать",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заказчик брони",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="reservation.table",
                        verbose_name="Номер стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
            },
        ),
    ]
