# Generated by Django 5.2 on 2025-05-11 05:39

import reservation.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Фамилия и имя сотрудника")),
                (
                    "photo_employee",
                    models.ImageField(
                        upload_to="photos/",
                        validators=[
                            reservation.validator.FileSizeValidator(),
                            reservation.validator.ImageFormatValidator(),
                        ],
                        verbose_name="Фото сотрудника",
                    ),
                ),
                ("job_title", models.CharField(max_length=200, verbose_name="Должность")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Комментарии о сотруднике")),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название ресторана")),
                (
                    "logo",
                    models.ImageField(
                        upload_to="photos/",
                        validators=[
                            reservation.validator.FileSizeValidator(),
                            reservation.validator.ImageFormatValidator(),
                        ],
                        verbose_name="Логотип ресторана",
                    ),
                ),
                ("story", models.TextField(verbose_name="История ресторана")),
                ("mission", models.TextField(verbose_name="Миссия")),
            ],
            options={
                "verbose_name": "ресторан",
                "verbose_name_plural": "рестораны",
            },
        ),
        migrations.AlterField(
            model_name="table",
            name="photo_table",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото стола",
                null=True,
                upload_to="photos/",
                validators=[reservation.validator.FileSizeValidator(), reservation.validator.ImageFormatValidator()],
                verbose_name="Изображение",
            ),
        ),
    ]
