# Generated by Django 5.2 on 2025-05-11 13:06

from django.db import migrations, models

import reservation.validator


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_employee_restaurant_alter_table_photo_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/",
                validators=[reservation.validator.FileSizeValidator(), reservation.validator.ImageFormatValidator()],
                verbose_name="Логотип ресторана",
            ),
        ),
    ]
