# Generated by Django 5.2 on 2025-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_restaurant_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание ресторана"),
        ),
    ]
