# Generated by Django 5.2 on 2025-05-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_restaurant_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "сотрудник", "verbose_name_plural": "сотрудники"},
        ),
    ]
